# Generated by Django 6.0.5 on 2026-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Code Postal'),
            preserve_default=False,
        ),
    ]
