# Generated by Django 6.0.5 on 2026-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
